configure: add mach time, support for FreeBSD, check for cc and pkg-config before using

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,5 @@
 #!/bin/sh
 
-echo Configuring Shairport
-
-rm -f config.mk config.h
-
-echo "// automatically generated file" > config.h
-
-LDFLAGS="${LDFLAGS} -lm -lpthread"
-
 export_config()
 {
     echo "#define $1" >> config.h
@@ -19,7 +11,7 @@ export_config()
 check_header()
 {
     echo "#include<$1>" > .header_test.c
-    if gcc -c .header_test.c > /dev/null 2>&1 /dev/null;  then
+    if cc -c .header_test.c > /dev/null 2>&1 /dev/null;  then
         echo "$1 found"
         if [ "$2" ]; then
             export_config $2
@@ -57,7 +49,65 @@ do_pkg_config()
     fi
 }
 
-do_pkg_config OpenSSL       openssl
+#figure out which time function to use
+check_time_function()
+{
+    cat >function_test.c <<FUNC_EOF
+#include <time.h>
+
+int main(int argc, char **argv){
+    struct timespec *tsp;
+    clock_gettime(CLOCK_MONOTONIC, tsp);
+}
+FUNC_EOF
+
+    if cc -c function_test.c > /dev/null 2>&1 /dev/null; then
+        echo "Found clock_gettime()"
+        echo -n "Checking if rt lib switch should be added: "
+        if cc function_test.c -lrt > /dev/null 2>&1 /dev/null; then
+            echo "-lrt works, adding"
+            LDFLAGS="${LDFLAGS} -lrt"
+        else
+            echo "-lrt not found, won't add"
+        fi
+    else
+        echo "Checking if we can use mach time"
+        check_header mach/mach.h
+        check_header mach/clock.h
+        export_config MACH_TIME
+    fi
+    rm -f function_test.*
+}
+
+# Check if command is installed
+check_command()
+{
+if command -v $1 > /dev/null 2>&1; then
+   echo $1 'is installed'
+else
+   echo $1 'is missing, cannot continue'
+   exit 1
+fi
+}
+
+echo Configuring Shairport
+rm -f config.mk config.h
+
+# First check if the tools configure needs are installed
+check_command pkg-config
+check_command cc
+
+echo "// automatically generated file" > config.h
+LDFLAGS="${LDFLAGS} -lm -lpthread"
+
+# On FreeBSD, OpenSSH is always there, but no .pc file is installed,
+# so pkg-config does not report it
+if [ `uname` = 'FreeBSD' ]; then
+   echo "FreeBSD machine, assuming OpenSSL is there"
+   LDFLAGS="${LDFLAGS} -lssl -lcrypto"
+else
+   do_pkg_config OpenSSL       openssl
+fi
 do_pkg_config libao         ao              CONFIG_AO
 do_pkg_config PulseAudio    libpulse-simple CONFIG_PULSE
 do_pkg_config ALSA          alsa            CONFIG_ALSA
@@ -76,6 +126,7 @@ if [ -z "$CONFIG_AVAHI" ]; then
     check_header  dns_sd.h      CONFIG_HAVE_DNS_SD_H
 fi
 
+check_time_function
 
 echo "CFLAGS+=${CFLAGS}" >> config.mk
 echo "LDFLAGS+=${LDFLAGS}" >> config.mk
